# Generated by Django 4.2 on 2023-04-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("password", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Monsieur"), ("female", "Madame")],
                        default="Monsieur",
                        max_length=32,
                    ),
                ),
                ("c_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "User",
                "ordering": ["c_time"],
            },
        ),
    ]
