# Generated by Django 4.2 on 2023-04-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("coach_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Tournoi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("place", models.CharField(max_length=200)),
                ("date_start", models.DateField(null=True)),
                ("date_end", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Poule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(default=0, max_length=20)),
                ("equipes", models.ManyToManyField(to="disks.equipe")),
                (
                    "tournoi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="disks.tournoi"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "equipe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disks.equipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(null=True)),
                ("place", models.CharField(max_length=200)),
                ("score1", models.IntegerField(default=0)),
                ("score2", models.IntegerField(default=0)),
                (
                    "equipe1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipe01",
                        to="disks.equipe",
                    ),
                ),
                (
                    "equipe2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipe02",
                        to="disks.equipe",
                    ),
                ),
            ],
        ),
    ]
