# Generated by Django 4.2 on 2023-04-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disks", "0002_match_poule"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournoi",
            old_name="place",
            new_name="location",
        ),
    ]
