# Generated by Django 4.2 on 2023-04-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disks", "0003_rename_place_tournoi_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="place",
            new_name="location",
        ),
    ]
